version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: uvicorn app.api:app  --host 0.0.0.0 --port 9003 --workers 8
    network_mode: "host"
    extra_hosts:
      - "localhost:127.0.0.1"
    depends_on:
      - memcached
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "10"
  memcached:
    image: memcached:latest
